### ISSUE TITLE
Propagate gulp-release errors to gulp task.

### ISSUE THREAD

**Issue by belicekm** [Aluxian/gulp-github-release#5]
This may be related to #3 , basically what I experience is that github-release errors are not propagated to my gulp task so my gulp task always succeeds.

I would expect some error thrown from gulp-github-release or some error event emitted.

My task:

```
gulp.task('release', function (callback) {
    return gulp.src('./dist/deploy.zip')
        .pipe(release({
            tag: latestTag,
            name: 'publish release ' + latestTag,
            notes: 'very good!',
            draft: false,
            prerelease: false,
            manifest: require('./package.json')
        }));
});

// the default task will log 'TEST' because 'release' task did not fail
gulp.task('default', ['release'], function () {
    console.log('TEST');
});
```

Output:

```
[10:38:02] Using gulpfile c:\Projects\github-experiments\gulpfile.js
[10:38:02] Starting 'release'...
[10:38:02] Using release tag: release-2.2.0
[10:38:02] Error: Error status: 401  response body:{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
 request details:{
  "uri": "https://api.github.com/repos/***/releases",
  "method": "POST",
  "json": true,
  "body": {
    "tag_name": "release-2.2.0",
    "name": "publish release release-2.2.0",
    "body": "very good!",
    "draft": false,
    "prerelease": false
  },
  "headers": {
    "Authorization": "token abc",
    "User-Agent": "publish-release 1.3.2 (https://github.com/remixz/publish-release)"
  }
}
    at Request._callback (C:\Projects\github-experiments\node_modules\publish-release\index.js:90:21)
    at Request.self.callback (C:\Projects\github-experiments\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Projects\github-experiments\node_modules\request\request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Projects\github-experiments\node_modules\request\request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
[10:38:02] Finished 'release' after 600 ms
[10:38:02] Starting 'default'...
default
[10:38:02] Finished 'default' after 137 μs
```

NOTE: github-release failed because authentication token in my environment is not valid

**Comment by aluxian** [comment]
You're right, the error is not handled correctly. Can you please try these changes: https://github.com/Aluxian/gulp-github-release/commit/d72ae9656cbf1008b1590c2932aadd82256d87e1

(quick and easy way to test: copy that index.js from GitHub and replace yours in node_modules/gulp-github-release)

**Comment by belicekm** [comment]
Tested but this solution throws max. stack size exceeded error.

```
> gulp
[12:17:30] Using gulpfile c:\Projects\github-experiments\gulpfile.js
[12:17:30] Starting 'release'...
[12:17:30] Using release tag: release-2.2.0
events.js:94
function emitOne(handler, isFn, self, arg1) {
                ^

RangeError: Maximum call stack size exceeded
    at emitOne (events.js:94:17)
    at PublishRelease.emit (events.js:188:7)
    at PublishRelease.<anonymous> (C:\Projects\github-experiments\node_modules\gulp-github-release\index.js:30:12)
    at emitOne (events.js:96:13)
    at PublishRelease.emit (events.js:188:7)
    at PublishRelease.<anonymous> (C:\Projects\github-experiments\node_modules\gulp-github-release\index.js:30:12)
    at emitOne (events.js:96:13)
    at PublishRelease.emit (events.js:188:7)
    at PublishRelease.<anonymous> (C:\Projects\github-experiments\node_modules\gulp-github-release\index.js:30:12)
    at emitOne (events.js:96:13)
```

Maybe it would be better to emit the error directly to the stream object:

```
...
 release.on('error', function(existingError) {
      stream.emit('error', existingError);
    });
...
```

For me error emitted to stream works like a charm:

```
> gulp
[12:18:05] Using gulpfile c:\Projects\github-experiments\gulpfile.js
[12:18:05] Starting 'release'...
[12:18:05] Using release tag: release-2.2.0
[12:18:06] 'release' errored after 589 ms
[12:18:06] Error: Error status: 401  response body:{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
 request details:{
  "uri": "https://api.github.com/repos/***/releases",
  "method": "POST",
  "json": true,
  "body": {
    "tag_name": "release-2.2.0",
    "name": "publish release release-2.2.0",
    "body": "very good!",
    "draft": false,
    "prerelease": false
  },
  "headers": {
    "Authorization": "token abc",
    "User-Agent": "publish-release 1.3.2 (https://github.com/remixz/publish-release)"
  }
}
...
```

**Comment by aluxian** [comment]
Ah, that's what I wanted to do! Thanks! I published the changes to npm
